#!/bin/bash

OUTPF=$(cat /etc/passwd | cut -d: -f1,3)
SMALL=$(cat /etc/passwd | cut -d: -f3)

echo ${OUTPF}
if [ 0 -ge $# ] ; then exit 1; fi

for ITEM in $SMALL ; do if [ $ITEM -eq $* ] ; then exit 0 ; fi
done
#optional:
#if fgrep -q $* <<< $SMALL ; then exit 0 ; else exit 1 ; fi
exit 1
